### ISSUE TITLE
How to use it as a drop-in replacement for CodecZlib (Zlib)

### ISSUE THREAD

**Issue by Moelf** [jakobnissen/LibDeflate.jl#1]
say I have the raw, compressed bytes: https://pastebin.com/GN8rFm3L

```julia
julia> a = UInt8[0x78, 0x01, 0xcd, 0x5b, 0x6f, ...

julia> transcode(ZlibDecompressor, a)
14460-element Vector{UInt8}: 0x40 0x00 0x38 0x78 ...
```

Was hoping I can do the same with LibDeflate with:
```julia

julia> decompress!(Decompressor(), zeros(UInt8, 14460), a)
ERROR: LibDeflateError("libdeflate 1: bad data")
Stacktrace:
```

**Comment by jakobnissen** [comment]
You can't. LibDeflate implements gzip and DEFLATE, not Zlib. I'm not 100% sure what format your data is in, but it's neither gzip nor DEFLATE.

Your options are:
* Use `GzipCompressor` from CodecZlib, this should work with LibDeflate's `gzip_decompress!`
* Use DEFLATE directly using LibDeflate, which CodecZlib does not support.
* Use LibDeflate to implement your own Zlib decoder (zlib is a wrapper format for DEFLATE, I think, so it shouldn't be too hard)

**Comment by Moelf** [comment]
tamasgal/UnROOT.jl#137

It turns out you can? Except there's 2 header bytes you want to remove first

**Comment by jakobnissen** [comment]
Oh nice! Cool. Maybe I should add that to the package.
If you can hang into the Compressor object instead of creating and destroying it at every compression, it should be even faster.
