### ISSUE TITLE
`decompress` size calculation limitations

### ISSUE THREAD

**Issue by li1** [jakobnissen/LibDeflate.jl#4]
Hey @jakobnissen, thanks for the cool library!

While playing around with it, I tried to `gzip_decompress!` a 2G (gzipped) file, which didn't work due to a `deflate_insufficient_space` error (it expands to ~13G). After digging around some more, I realized that the uncompressed file size calculation is going to be off for everything > `2^32` bytes.

You're checking the gzip's `ISIZE` field here: https://github.com/jakobnissen/LibDeflate.jl/blob/master/src/gzip.jl#L324
According to the gnu docs, the `ISIZE` is calculated using `uncompressed_size % (2^32)`, so everything > 4GiB will wrap.

From the gzip docs:
> The gzip format represents the input size modulo 2^32, so the uncompressed size and compression ratio are listed incorrectly for uncompressed files 4 GiB and larger. To work around this problem, you can use the following command to discover a large uncompressed file’s true size:
> zcat file.gz | wc -c
_https://www.gnu.org/software/gzip/manual/gzip.html#index-options-4_

I wonder if it makes sense to warn about that in the docstring. I'm not sure if it can be fixed easily (there's simply information loss, so I think there's no other way than using something like `zcat` to recover that info) 🤷

**Comment by jakobnissen** [comment]
Good idea, I've amended the README now. Sorry for only seeing this issue today
